### PR TITLE
Merging downstream work on offsets

### PR DESCRIPTION
**Pull request by srerickson**
I noticed  some problems I encountered with offsets were resolved downstream and wanted to merge this work if possible ...

### CODE REVIEW

**Comment by mehanizm** [comment]
@srerickson , thanks a lot for your work!

Unfortunately, I cannot merge commits right now due to mistake in the module name and lack of the tests. If you can do that it would be great. Otherwise I'll get things done at the weekend.

**Comment by srerickson** [comment]
I'll work on a separate pull request with tests that isn't based on third party commits.

**Comment by mehanizm** [comment]
Thank you!

**Comment by mehanizm** [comment]
@srerickson I've committed all the stuff recently. Please, update your sources to the actually version of the lib 0.2.1+

**Comment by srerickson** [comment]
thanks so much!

**Pull request closed without merging**
